### ISSUE TITLE
RNFetchBlob.fetch doesn't work

### ISSUE THREAD

**Issue by hand-shengwang** [joltup/rn-fetch-blob#375]
"react": "16.8.3",
"react-native": "0.59.2",
"rn-fetch-blob": "^0.10.15"

RNFetchBlob.fetch('POST',url,{
            'Authorization':`Bearer ${access_token}`,
            'Content-Type' : 'multipart/form-data',
            'Accept': 'application/json'
        },params).uploadProgress((written, total) => {
            if(__DEV__) console.log('uploaded', written / total)
        }).then((res)=>{
            success(res);
        }).catch((err)=>{
            failure(err);
        });
    } catch (err){
        if(__DEV__) console.log(err)
        failure(err);
    }

**Comment by Jhonsebas77** [comment]
Still don't work in Android, in iOS work fine

   ```
   "react": "16.8.6",
   "react-native": "0.57.8",
   "rn-fetch-blob": "^0.10.15"
    classpath 'com.android.tools.build:gradle:3.1.4'
```

**Comment by Frekansapp** [comment]
I merged some PRs into this repo you could try it https://github.com/Frekansapp/rn-fetch-blob

**Comment by Jhonsebas77** [comment]
Thanks @Frekansapp,  with your repo still don't work in Android, they stay in _fetch_ method

**Comment by Jhonsebas77** [comment]
@hand-shengwang Have you been able to solve the problem?

**Comment by bockc** [comment]
I currently have the same issue in `react-native 0.59.9` and `rn-fetch-blob 0.10.15`
It works like a charm on iOS but fails on Android. My GET request takes ages to fail (between 5-10mn !!) with the following error: `Error: Download manager failed to download from 'http://myadress' Status Code = 16`

I can confirm that @Frekansapp fork does not solve the issue.

Did any of you find a fix ?
